version: "3.7"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./services/db:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "applied_portal"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password"

volumes:
  mysql-data:
